language: cpp
compiler:
  - gcc
  - clang
env:
  - CONFIG=debug QT5=qt5
  - CONFIG=release
  - CONFIG=release QT5=qt5
before_install:
  - if [[ -z \"${QT5}\" ]]; then sudo apt-get update -qq; sudo apt-get install libqt4-dev qt4-qmake; else sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa; sudo apt-get update -qq; sudo apt-get install qtbase5-dev qt5-default qttools5-dev-tools;fi
  - qmake -version
script:
 - qmake nestorthelogger.pro
 - make
