language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install qtbase5-dev
#  - sudo apt-get install libqt4-dev qt4-qmake
  - qmake -version
script:
 - qmake nestorthelogger.pro
 - make
